"""Add image_url to BlogPost

Revision ID: 14c9d3aa74f0
Revises: 7fe83ee91881
Create Date: 2025-07-07 17:19:49.587287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c9d3aa74f0'
down_revision = '7fe83ee91881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
